trigger:
  branches:
    include:
    - main
    - master
  paths:
    include:
    - SWE-Sub2/*
    - azure-pipelines-sub2.yml

variables:
  buildConfiguration: 'Release'
  solution: 'SWE-Sub2/SWE-Sub2.sln'
  webAppName: 'swe-sub2'

pool:
  vmImage: windows-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: './SWE-Sub2/my-app'

- task: CmdLine@2
  displayName: 'ng build'
  inputs:
    script: |
      npx ng build --base-href /s2/ --output-path=./../SWE-Sub2/wwwroot
    workingDirectory: './SWE-Sub2/my-app'

- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    
- task: DotNetCoreCLI@2
  displayName: Restore & Build
  inputs:
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'BDE (Dev/Test Pay-As-You-Go)(0257f04b-f0e4-41e7-bb0f-0f8d3d2ac423)'
    appType: 'webApp'
    WebAppName: '$(webAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
